name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ARM64
            arch: aarch64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          autoconf automake libtool build-essential \
          asciidoc xmlto wget

    - name: Install Static glibc
      run: |
        wget https://github.com/static-linux/static-glibc/releases/download/2.35-1/static-glibc-2.35-1-${{ matrix.arch }}.tar.gz
        mkdir -p /opt/static-glibc
        tar -xzf static-glibc-2.35-1-${{ matrix.arch }}.tar.gz -C /opt/static-glibc
        export PATH=/opt/static-glibc/bin:$PATH

    - name: Build Static libev
      run: |
        wget https://dist.schmorp.de/libev/Attic/libev-4.33.tar.gz
        tar -xzf libev-4.33.tar.gz
        cd libev-4.33
        ./configure CC=/opt/static-glibc/bin/gcc --enable-static --disable-shared
        make
        sudo make install

    - name: Build Binary
      run: |
        git submodule update --init --recursive
        ./autogen.sh
        ./configure CC=/opt/static-glibc/bin/gcc --prefix=/usr --enable-static --disable-shared \
            LDFLAGS="-static -L/usr/local/lib" \
            CPPFLAGS="-I/usr/local/include"
        make
        strip src/obfs-server

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: obfs-server-${{ matrix.arch }}
        path: src/obfs-server

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: src/

    - name: Prepare Release
      run: |
        mkdir -p src/release
        mv src/obfs-server-aarch64/obfs-server src/release/obfs-server-aarch64
        mv src/obfs-server-x86_64/obfs-server src/release/obfs-server-x86_64

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ github.ref_name }}
        files: src/release/*