name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          build-essential autoconf libtool libssl-dev \
          libpcre3-dev libev-dev asciidoc xmlto automake \
          musl-tools \
          libmnl-dev \
          libnfnetlink-dev \
          libxtables-dev \
          libip6tc-dev \
          libip4tc-dev \
          libnetfilter-conntrack-dev \
          libnetfilter-queue-dev

    - name: Build
      run: |
        git submodule update --init --recursive
        ./autogen.sh
        ./configure --host=x86_64-linux-musl
        make

    - name: Strip
      run: strip src/obfs-server

    - name: Upload Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ github.ref_name }}
        files: src/obfs-server
        name: obfs-server-${{ github.ref_name }}