name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            arch: x86_64
          - os: ARM64
            arch: aarch64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Remove problematic PPA
      run: |
        sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test
        sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install --no-install-recommends -y \
          build-essential autoconf libtool libssl-dev \
          libpcre3-dev libev-dev asciidoc xmlto automake

    - name: Build
      run: |
        git submodule update --init --recursive
        ./autogen.sh
        export LIBS="-lpthread -lm"
        export LDFLAGS="-Wl,-static -static -static-libgcc -no-pie"
        ./configure --prefix=/usr --disable-documentation && make
        strip src/obfs-server

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: obfs-server-${{ matrix.arch }}
        path: src/obfs-server

  release:
    runs-on: ubuntu-20.04
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        path: src/

    - name: Move and prepare release
      run: |
        mkdir -p src/release
        mv src/obfs-server-aarch64/obfs-server src/release/obfs-server-aarch64
        mv src/obfs-server-x86_64/obfs-server src/release/obfs-server-x86_64

    - name: Create GitHub release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ github.ref_name }}
        files: src/release/*