name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ARM64
            arch: aarch64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          autoconf automake libtool libev-dev asciidoc xmlto \
          build-essential

    - name: Prepare Sources
      run: |
        git submodule update --init --recursive
        ./autogen.sh

    - name: Build
      run: |
        ./configure --prefix=/usr --enable-static --disable-shared LDFLAGS="-static"
        make
        strip src/obfs-server

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: obfs-server-${{ matrix.arch }}
        path: src/obfs-server

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: src/

    - name: Prepare Release
      run: |
        mkdir -p src/release
        mv src/obfs-server-aarch64/obfs-server src/release/obfs-server-aarch64
        mv src/obfs-server-x86_64/obfs-server src/release/obfs-server-x86_64

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ github.ref_name }}
        files: src/release/*