name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_x86_64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          build-essential autoconf libtool libssl-dev \
          libpcre3-dev libev-dev asciidoc xmlto automake

    - name: Build x86_64 Binary
      run: |
        git submodule update --init --recursive
        ./autogen.sh
        ./configure && make
        strip src/obfs-server
        mv src/obfs-server src/obfs-server-x86_64

    - name: Upload x86_64 Binary
      uses: actions/upload-artifact@v3
      with:
        name: obfs-server-x86_64
        path: src/obfs-server-x86_64

  build_aarch64:
    runs-on: oracle-nrt2
    needs: build_x86_64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          build-essential autoconf libtool libssl-dev \
          libpcre3-dev libev-dev asciidoc xmlto automake

    - name: Build aarch64 Binary
      run: |
        git submodule update --init --recursive
        ./autogen.sh
        ./configure && make
        strip src/obfs-server
        mv src/obfs-server src/obfs-server-aarch64

    - name: Upload aarch64 Binary
      uses: actions/upload-artifact@v3
      with:
        name: obfs-server-aarch64
        path: src/obfs-server-aarch64

  release:
    runs-on: ubuntu-latest
    needs: [build_x86_64, build_aarch64]

    steps:
    - name: Download Binaries
      uses: actions/download-artifact@v3
      with:
        name: obfs-server-x86_64
        path: src/
    
    - name: Download aarch64 Binary
      uses: actions/download-artifact@v3
      with:
        name: obfs-server-aarch64
        path: src/

    - name: Upload Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          src/obfs-server-x86_64
          src/obfs-server-aarch64