name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          build-essential autoconf libtool libssl-dev \
          libpcre3-dev libev-dev asciidoc xmlto automake

    - name: Build Binaries
      run: |
        git submodule update --init --recursive
        ./autogen.sh
        architectures=("x86_64" "aarch64")       
        for arch in "${architectures[@]}"; do
          ./configure --host=${arch}-linux-gnu
          make
          strip src/obfs-server
          mv src/obfs-server "src/obfs-server-${arch}"
          make clean
        done

    - name: Upload Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          src/obfs-server-x86_64
          src/obfs-server-aarch64