name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ARM64]
        arch: [x86_64, aarch64]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          build-essential autoconf libtool libssl-dev \
          libpcre3-dev libev-dev asciidoc xmlto automake

    - name: Build Binary
      run: |
        git submodule update --init --recursive
        ./autogen.sh
        ./configure && make
        strip src/obfs-server

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: obfs-server-${{ matrix.arch }}
        path: src/obfs-server

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Binary
      uses: actions/download-artifact@v3
      with:
        name: obfs-server-${{ matrix.arch }}
        path: src/

    - name: Upload Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          src/obfs-server-*