name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ARM64
            arch: aarch64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          build-essential autoconf libtool libssl-dev \
          libpcre3-dev libev-dev asciidoc xmlto automake \
          gcc-7 g++-7 wget curl

    - name: Install GCC 7
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 100

    - name: Build
      run: |
        git submodule update --init --recursive
        ./autogen.sh
        export LIBS="-lpthread -lm"
        export LDFLAGS="-Wl,-static -static-libgcc -static-libstdc++ -no-pie"
        ./configure --prefix=/usr --disable-documentation && make
        strip src/obfs-server

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: obfs-server-${{ matrix.arch }}
        path: src/obfs-server

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download
      uses: actions/download-artifact@v3
      with:
        path: src/

    - name: Move
      run: |
        mkdir -p src/release
        mv src/obfs-server-aarch64/obfs-server src/release/obfs-server-aarch64
        mv src/obfs-server-x86_64/obfs-server src/release/obfs-server-x86_64

    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ github.ref_name }}
        files: src/release/*